title: EEROS
icon: 🌬
project: EEROS_SETEC_Params_niveau2
database: Raccordement_DC_CM1
root_activity: fabrication_et_pertes_electriques_liaison_entiere

impacts:
  climate_change: ['EF v3.0','climate change','global warming potential (GWP100)']
  particules: ['EF v3.0','particulate matter formation','impact on human health']
  mineral_depletion: ['EF v3.0','material resources: metals/minerals','abiotic depletion potential (ADP): elements (ultimate reserves)']
  acidification: ['EF v3.0','acidification','accumulated exceedance (ae)']
  toxicity_non_carcinogenic: ['EF v3.0','human toxicity: non-carcinogenic','comparative toxic unit for human (CTUh) ']
  toxicity_carcinogenic: ['EF v3.0','human toxicity: carcinogenic','comparative toxic unit for human (CTUh) ']
  land_use: ['EF v3.0', 'land use', 'soil quality index']

functional_units:
    system:
        formula: 1
        unit:
    energydelivered:
        formula: elec_delivree_MWh_par_an*duree_de_vie_liaison
        unit: kWh      

axes: ["system_1","phase"]

